### ISSUE TITLE
Charater says one of dialogs only in one place in initial guards room

### ISSUE THREAD

**Issue by PPat93** [metal-kosz/nes#4]
In the initial guards room, character is saying one o his dialogs only in specified place. It is located on one square instead on whole way out. Maybe on doors would be better? It is easy to miss the dialog and player may loose some part of immersion. Details on screen:
![dialog](https://user-images.githubusercontent.com/45639693/114287791-1d141b80-9a6a-11eb-9a77-160873a4b861.png)

**Comment by metal-kosz** [comment]
event moved to square with stairs and fixed typo in dialogue (commit 974b506)

**Comment by PPat93** [comment]
Fixed, works like a charm.
![fixed](https://user-images.githubusercontent.com/45639693/114759854-f9e5b680-9d5e-11eb-99b8-ddb89c8592f4.png)
